version: '3'
services:
  app:
    container_name: 'home-app'
    image: 'home-app-image'
    restart: unless-stopped
    ports:
      - '9094:80'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  default:
    name: home_default