version: '3'

services:
    app:
        container_name: 'home-app'
        image: home-box-image
        restart: unless-stopped
        ports:
            - '82:80'
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ConnectionString=host=192.168.1.161;port=5432;database=home_app;username=postgres;password=qG^zzCXry9ZVuvauciU*;Pooling=true;
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
            - /home/miloszdura:/host
networks:
    default:
        name: home_default