services:

    home-app:
        image: citr0s/home-app
        ports:
            - '82:80'
        env_file:
            - '.env'
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:80
            - ASPNETCORE_CONNECTION_STRING=host=${POSTGRES_HOST};port=5432;database=home_app;username=${POSTGRES_USER};password=${POSTGRES_PASSWORD};Pooling=true;
            - ASPNETCORE_MINIO_ENDPOINT=${MINIO_HOST}
            - ASPNETCORE_MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - ASPNETCORE_MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
            - ASPNETCORE_MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
            - ASPNETCORE_MINIO_CDN_URL=${MINIO_CDN_URL}
            - ASPNETCORE_WEATHER_API_KEY=${WEATHER_API_KEY}
            - ASPNETCORE_MAPS_API_KEY=${MAPS_API_KEY}
        volumes:
            - ./app-data:/data
            - ./letsencrypt:/etc/letsencrypt
        depends_on:
            - postgres
            - minio

    postgres:
        image: postgres:15.12
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data/

    minio:
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9002:9001"
        environment:
            - MINIO_ROOT_USER=root_user
            - MINIO_ROOT_PASSWORD=root_password
        command: server --address ":9000" --console-address ":9001" /data
        volumes:
            - ./minio-data/minio:/data