name: Build

on:
    pull_request:
        branches: [ "main" ]

env:
    CHROME_BIN: /usr/bin/chromium-browser

jobs:

    build-fe:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v4

            -   name: Installing Yarn packages
                run: yarn --prefer-offline

            -   name: Compiling FE
                run: npm run build

    build-be:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '8.0.x'

            -   name: Testing BE
                run: dotnet build api/home-box-landing/HomeBoxLanding.sln

    #test-fe:
    #    runs-on: self-hosted

    #    steps:
    #        -   uses: actions/checkout@v4

    #        -   name: Installing Yarn packages
    #            run: yarn --prefer-offline

    #        -   name: Testing FE
    #            run: npm run test-ci

    test-be:
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: '8.0.x'

            -   name: Testing BE
                run: dotnet test api/home-box-landing/HomeBoxLanding.sln

    lint-fe:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v4

            -   name: Installing Yarn packages
                run: yarn --prefer-offline

            -   name: Linting FE
                run: npm run lint

    docker-test:
        runs-on: self-hosted
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Log in to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Build Docker image
                run: |
                    docker build -t ${{ secrets.DOCKER_USERNAME }}/home-app:latest . --platform linux/amd64

