name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Installing NPM packages
      run: npm i
    - name: Compiling assets
      run: npm run ng b
    - name: Build the Docker image
      run: docker build . --file Dockerfile
