name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        script: |
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install

    - name: Compiling assets
      run: npm run ng b

    - name: Build the Docker image
      run: docker build . --file Dockerfile
