name: Docker Image CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CHROME_BIN: /usr/bin/chromium-browser

jobs:

    #setup:
    #    runs-on: self-hosted
    #    steps:
    #        -   uses: actions/checkout@v3

    #        -   name: Installing Yarn packages
    #            run: yarn

    build:
        #needs: setup
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Installing Yarn packages
                run: yarn

            -   name: Compiling FE
                run: npm run build

            -   name: Build the Docker image
                run: docker build . --file Dockerfile

    #test:
        #needs: setup
        #runs-on: self-hosted

        #steps:
            #-   uses: actions/checkout@v3

            #-   name: Installing Yarn packages
            #    run: yarn

            #-   name: Testing FE
            #    run: npm run test-ci

            #-   name: Testing BE
            #    run: dotnet test api/home-box-landing/HomeBoxLanding.sln

    lint:
        needs: setup
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Installing Yarn packages
                run: yarn

            -   name: Linting FE
                run: npm run lint
