name: Docker Image CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CHROME_BIN: /usr/bin/chromium-browser

jobs:

    build-fe:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Installing Yarn packages
                run: yarn

            -   name: Compiling FE
                run: npm run build

    build-be:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Testing BE
                run: dotnet build api/home-box-landing/HomeBoxLanding.sln

    test-fe:
        needs: build-fe
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v3

            -   name: Installing Yarn packages
                run: yarn

            -   name: Testing FE
                run: npm run test-ci

    test-be:
        needs: build-be
        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v3

            -   name: Testing BE
                run: dotnet test api/home-box-landing/HomeBoxLanding.sln

    lint-fe:
        needs: test-fe
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Installing Yarn packages
                run: yarn

            -   name: Linting FE
                run: npm run lint

    docker-build-test:
        needs: lint-fe
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3

            -   name: Build the Docker image
                run: docker build . --file Dockerfile
