name: Docker Image CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CHROME_BIN: /usr/bin/chromium-browser

jobs:

    build:

        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v3

            -   name: Installing Yarn packages
                run: yarn

            -   name: Compiling FE
                run: npm run ng b

            -   name: Build the Docker image
                run: docker build . --file Dockerfile

    test:

        runs-on: self-hosted

        steps:
            -   uses: actions/checkout@v3

            -   name: Installing Yarn packages
                run: yarn

            -   name: Testing FE
                run: npm run test-ci

            -   name: Testing BE
                run: dotnet test api/home-box-landing/HomeBoxLanding.sln
